[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "."

[build.environment]
  PYTHON_VERSION = "3.8"

[[plugins]]
  package = "@netlify/plugin-python"

[[redirects]]
  from = "/*"
  to "/.netlify/functions/app"
  status = 200 