[build]
  command = """
    pip install --upgrade pip
    pip install -r requirements.txt
  """
  publish = "public"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-python" 