[build]
  command = "npm install && pip install -r requirements.txt"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.8"
  PYTHON_RUNTIME = "python3.8"
  PIP_USER = "0"

[[plugins]]
  package = "@netlify/plugin-python"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 