[build]
  command = "pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.8.12"
  PYTHON_RUNTIME = "python3.8"

[[plugins]]
  package = "@netlify/plugin-python"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" 